### ISSUE TITLE
How to make single predictions?

### ISSUE THREAD

**Issue by alishakiba** [JeffreyDF/kaggle_diabetic_retinopathy#1]
Hi Dear Jeffery

In your IPython notebook, you have given instructions for predicting a set of images using a GPU implementation. However, I have used the weights and loaded the data into the network and want to make predictions for images one at a time, since I do not have access to GPUs.

I think this might be possible by the following code, but it is not! Could you please help!

Thanks in advance

```
img = np.array(Image.open(r'/home/ali/Desktop/data/train/1099_right.jpeg')).T / 255.0
xs_shared[0].set_value(img[np.newaxis, :, :, :])
xs_shared[1].set_value(np.matrix([[512, 512]]))
compute_output(0)
```

**Comment by JeffreyDF** [comment]
Hi alishakiba,

Keep in mind that the architecture needs at least two images (left and right eye of same patient, ideally), but you could use the same image twice, for example. You could also rewrite the architecture to only use a batch size of 2, that should work.

I think the code could be cleaned up quite a bit but I probably won't have time soon to do this. Nevertheless, let me know if it still doesn't work and I'll try to find some time to make something quickly that works on the CPU. 

Jeffrey
