### ISSUE TITLE
questions about the datasets provided by the Kaggle

### ISSUE THREAD

**Issue by oukohou** [JeffreyDF/kaggle_diabetic_retinopathy#3]
Sorry to bother, and maybe too late, but I did encounter a question about the datasets, not sure how you labeld the train datasets? cause what I got for train datasets look like this : 
![1](https://cloud.githubusercontent.com/assets/16237619/20452929/480acfc8-ae51-11e6-8d31-264773fdd7d4.png)

and train.zip.001 contains 35126 images , while 
train.zip.002 8394
train.zip.003 8482
train.zip.004 8415
train.zip.001 1427
I didn't figure out how the data is labeld ?
any help will be hihgly appreciated.

**Comment by oukohou** [comment]
Well , this is embrassing. I realized that it's because I didn't read the `trainLabels.csv` file, which tells every image belongs to which label,
So close it now.
Again, sorry to bother.

**Comment by oukohou** [comment]
reopened this to show the trainLabels.csv file:
![image](https://cloud.githubusercontent.com/assets/16237619/20473923/a9e8a5c2-affe-11e6-8634-be99ce720a9e.png)
just in case anybody encounter the same embrassment.....

**Comment by axiqia** [comment]
@oukohou 
Dear oukohou:
I'm so sorry to bother you.I download the file from this website, and follow the instruction in your ipython notebook, but get some problem. The generators.py include some code about prefix:

def patches_gen_pairs_pseudolabel(images, labels, p_x=80, p_y=80, num_channels=3, chunk_size=1024, num_chunks=100, rng=np.random, prefix_train='data/train_ds5_crop/', prefix_test='data/test_ds5_crop/', transfo_params=None, paired_transfos=False): num_patients = len(images)

but there is no file named train_ds5_crop and test_ds5_crop, and only tranlabel.

what should i do?

I'm new to Deep Learning .Thanks a lot if you can help me , sincerely!

Shawn

**Comment by oukohou** [comment]
Dear Shawn:
sorry I replied too late, but not sure what do you mean? I just issued an issue about the project https://github.com/JeffreyDF/kaggle_diabetic_retinopathy , while I didn't write this project...
And cause when I issued that issue, I'm using java to do this classification, so I also didn't run the project myself,  so perhaps I can't help more for you . regret.. 
Maybe you are looking for the writer's help? Then I got his profile as this link :  https://github.com/JeffreyDF , hope that helps.
If anything happens, I will be appreciated of being emailed, feel free to email me.
And welcome to communicate with me, I'm right now doing  some deeplearning work on tensorflow, maybe we can help each other and go fuether.
 my pleasure to be of any help.


your, 
Sincerely.




------------------ 原始邮件 ------------------
发件人: "axiqia";<notifications@github.com>;
发送时间: 2017年3月20日(星期一) 下午5:34
收件人: "JeffreyDF/kaggle_diabetic_retinopathy"<kaggle_diabetic_retinopathy@noreply.github.com>; 
抄送: "六步官人"<oukohou@qq.com>; "Mention"<mention@noreply.github.com>; 
主题: Re: [JeffreyDF/kaggle_diabetic_retinopathy] questions about thedatasets provided by the Kaggle (#3)




@oukohou
 Dear oukohou:
 I'm so sorry to bother you.I download the file from this website, and follow the instruction in your ipython notebook, but get some problem. The generators.py include some code about prefix:
 
def patches_gen_pairs_pseudolabel(images, labels, p_x=80, p_y=80, num_channels=3, chunk_size=1024, num_chunks=100, rng=np.random, prefix_train='data/train_ds5_crop/', prefix_test='data/test_ds5_crop/', transfo_params=None, paired_transfos=False): num_patients = len(images)
 
but there is no file named train_ds5_crop and test_ds5_crop, and only tranlabel.
 
what should i do?
 
I'm new to Deep Learning .Thanks a lot if you can help me , sincerely!
 
Shawn

**Comment by axiqia** [comment]
Hi oukohou：
So glad could hear from you.I have spend around a week to bulid development environment with theano, lasagne and cuda which is really torturous. After that, I have tried to email the writer but didn't received yet(:


I am a novice in this ML, maybe I will trouble you a lot :) .


And i will email you, if i fixed it.


yours, 
Sincerely. 


------------------ 原始邮件 ------------------
发件人: "oukohou";<notifications@github.com>;
发送时间: 2017年3月21日(星期二) 下午2:23
收件人: "JeffreyDF/kaggle_diabetic_retinopathy"<kaggle_diabetic_retinopathy@noreply.github.com>; 
抄送: "╰☆╮兮恰♫ "<1274561783@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [JeffreyDF/kaggle_diabetic_retinopathy] questions about thedatasets provided by the Kaggle (#3)



Dear Shawn: 
 sorry I replied too late, but not sure what do you mean? I just issued an issue about the project https://github.com/JeffreyDF/kaggle_diabetic_retinopathy , while I didn't write this project... 
 And cause when I issued that issue, I'm using java to do this classification, so I also didn't run the project myself,  so perhaps I can't help more for you . regret..  
 Maybe you are looking for the writer's help? Then I got his profile as this link :  https://github.com/JeffreyDF , hope that helps. 
 If anything happens, I will be appreciated of being emailed, feel free to email me. 
 And welcome to communicate with me, I'm right now doing  some deeplearning work on tensorflow, maybe we can help each other and go fuether. 
  my pleasure to be of any help. 
 
 
your, 
Sincerely. 
 
 
 
 
 ------------------ 原始邮件 ------------------ 
 发件人: "axiqia";<notifications@github.com>; 
 发送时间: 2017年3月20日(星期一) 下午5:34 
 收件人: "JeffreyDF/kaggle_diabetic_retinopathy"<kaggle_diabetic_retinopathy@noreply.github.com>;  
 抄送: "六步官人"<oukohou@qq.com>; "Mention"<mention@noreply.github.com>;  
 主题: Re: [JeffreyDF/kaggle_diabetic_retinopathy] questions about thedatasets provided by the Kaggle (#3) 
 
 
 
 
 @oukohou 
  Dear oukohou: 
  I'm so sorry to bother you.I download the file from this website, and follow the instruction in your ipython notebook, but get some problem. The generators.py include some code about prefix: 
   
 def patches_gen_pairs_pseudolabel(images, labels, p_x=80, p_y=80, num_channels=3, chunk_size=1024, num_chunks=100, rng=np.random, prefix_train='data/train_ds5_crop/', prefix_test='data/test_ds5_crop/', transfo_params=None, paired_transfos=False): num_patients = len(images) 
   
 but there is no file named train_ds5_crop and test_ds5_crop, and only tranlabel. 
   
 what should i do? 
   
 I'm new to Deep Learning .Thanks a lot if you can help me , sincerely! 
   
 Shawn

**Comment by JeffreyDF** [comment]
Hi all,

This is assuming you use the data from the competition (https://www.kaggle.com/c/diabetic-retinopathy-detection). 'train_ds5_crop' is produced by the script here: https://github.com/JeffreyDF/kaggle_diabetic_retinopathy/blob/master/ds_images_train.py. It does some preprocessing, downscalling and tries to crop the black borders from the images.

Jeffrey

**Comment by axiqia** [comment]
Hi Jeffery，


I'm really so glad to receive your reply. And I think it's may help a lot.
It' to late tonight, I'll try it tommorm morning.
Thank you so much.


Shawn




------------------ 原始邮件 ------------------
发件人: "Jeffrey De Fauw";<notifications@github.com>;
发送时间: 2017年3月25日(星期六) 晚上11:53
收件人: "JeffreyDF/kaggle_diabetic_retinopathy"<kaggle_diabetic_retinopathy@noreply.github.com>; 
抄送: "╰☆╮兮恰♫ "<1274561783@qq.com>; "Comment"<comment@noreply.github.com>; 
主题: Re: [JeffreyDF/kaggle_diabetic_retinopathy] questions about thedatasets provided by the Kaggle (#3)




Hi all,
 
This is assuming you use the data from the competition (https://www.kaggle.com/c/diabetic-retinopathy-detection). 'train_ds5_crop' is produced by the script here: https://github.com/JeffreyDF/kaggle_diabetic_retinopathy/blob/master/ds_images_train.py. It does some preprocessing, downscalling and tries to crop the black borders from the images.
 
Jeffrey
