### ISSUE TITLE
No file in the directory data/train_ds5_crop

### ISSUE THREAD

**Issue by axiqia** [JeffreyDF/kaggle_diabetic_retinopathy#4]
Dear Jeffrey:
I'm so sorry to bother you.I download the file from this website, and follow the instruction in your ipython notebook, but get some problem. The generators.py include some code about prefix:

`
def patches_gen_pairs_pseudolabel(images, labels, p_x=80, p_y=80,
                                  num_channels=3, chunk_size=1024,
                                  num_chunks=100, rng=np.random,
                                  prefix_train='data/train_ds5_crop/',
                                  prefix_test='data/test_ds5_crop/',
                                  transfo_params=None,
                                  paired_transfos=False):
    num_patients = len(images)
`

but there is no file named train_ds5_crop and test_ds5_crop, and only tranlabel.

what should i do?

I'm new to Deep Learning .Thanks a lot if you can help me , sincerely!

Shawn

**Comment by JeffreyDF** [comment]
Hi,

See my response here: https://github.com/JeffreyDF/kaggle_diabetic_retinopathy/issues/3.

Jeffrey
